### ISSUE TITLE
Script downloading https://plays.tv/game/* urls

### ISSUE THREAD

**Issue by lowlevelm** [ArchiveTeam/playstv-grab#1]
The script is downloading https://plays.tv/game/* urls, resulting in thousands of blank pages.
To remedy this, the script should check if the url matches https://plays.tv/game/*, and if it does, skip downloading the url.

Bug reported by Marked, and the log is at: https://paste.ubuntu.com/p/3WSX4pKfXW/

**Comment by Arkiver2** [comment]
fixed with af34b9eef7aaad7bfb0d39aba204f67ca018ac5b note the comment at https://github.com/ArchiveTeam/playstv-grab/pull/2#issuecomment-563480387
